from django.apps import AppConfig


class MyappConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'myApp'




'''
NOTE
Significance: Defines the configuration for your app. Normally, you don't need to modify this unless you have specific configurations.
What to write: Usually auto-generated by Django.
'''